### ISSUE TITLE
bump default ceph version

### ISSUE THREAD

**Issue by ricolin** [vexxhost/ansible-collection-ceph#13]
As Ceph [Pacific](https://docs.ceph.com/en/latest/releases/pacific) is eol now, we should consider move the default version to [Quincy](https://docs.ceph.com/en/latest/releases/quincy)

**Comment by mnaser** [comment]
We default to [18.2.1](https://github.com/vexxhost/ansible-collection-ceph/blob/v3.0.0/playbooks/site.yml#L26) right now :)
