### ISSUE TITLE
Ansible Collection publish failed

### ISSUE THREAD

**Issue by ricolin** [vexxhost/ansible-collection-ceph#23]
there's a error block ansible-collection-ceph from publish https://github.com/vexxhost/ansible-collection-ceph/actions/runs/7425054349/job/20253763886
```Error when finding available api versions from default (https://galaxy.ansible.com) (HTTP Code: 403, Message: Forbidden)```

**Comment by mnaser** [comment]
https://galaxy.ansible.com/ui/repo/published/vexxhost/ceph/
